from .state import *
from .iniciapantalla import *
from .quitapantalla import *
from .imprimescreen import *
from .esperacualquiertecla import *
from .colores import *
from .borrapantalla import *
from .pixel import *
from .linea import *
